name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -c constraints.txt pylint
        pip install -c constraints.txt tensorflow==2.6.0
        pip install wand==0.6.7
    - name: Analysing the code with pylint
      run: |
        pylint `ls -R|grep .py$|xargs`
